MD013: false   # Line length must be < 80 
MD024: false   # Multiple headings with the same contentm
MD033: false   # Inline HTML is not allowed
MD041: false   # First line in file should be a top level heading h1
