MD013: false   # Line length must be < 80 
MD024: false   # Multiple headings with the same content
MD029: false   # Ordered list item prefix [Expected: 2; Actual: 11]
MD033: false   # Inline HTML is not allowed
MD041: false   # First line in file should be a top level heading h1
