# Site name
site_name: Module 6 - Data Operations
site_url: https://qaalabs.github.io/DE5M6/
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Overview: index.md
  - Module KSBs: ksb.md

  - Agenda:
    - Topics: agenda/index.md
    - Day 3: agenda/day3.md

  - "Day 3 - Quality & Governance":
    - "Data Quality Dimensions": day3/quality-dimensions.md
    - "Setup MS Fabric Playground": labs/run-inside-vm.md
    - "Lab 3.1 ~ Medallion Architecture": labs/31-medallion.md
    - "Lab 3.2 ~ 21 Deployment Pipelines": labs/21-deployment-pipelines.md
    - "Technical Debt Audit": day3/technical-debt-activity.md

  - Resources: resources.md

not_in_nav: |
  404.md
  trainer.md
  DAY-setup.md
  day1/system-failure.md
  day1/why-monitor.md
  day1/status-page-analysis.md
  day1/monitoring-tools.md
  day1/cloud-monitoring-report-back.md
  day2/system-broke.md
  day2/ai-de.md
  day2/fire-drill-briefing.md
  day2/fire-drill-groups.md
  day2/scenario1-debrief.md
  day2/scenario2-debrief.md
  day3/good-data.md
  day3/data-quality.md
  day3/quality-patterns.md
  day3/technical-debt.md
  day3/tech-debt-issues.md
  day3/debt-controls.md
  day4/quality-tools-trainer.md
  day1/10-clone-repo.md
  day2/20-clone-repo.md
  day2/group-blaze.md
  day2/group-ember.md
  day2/group-ignis.md
  day2/group-mistral.md


# Theme
theme:
    features:
      - toc.integrate
      - content.code.copy
    name: material
    icon:
      logo: material/database

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: false
      toc_depth: 2

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - glightbox
  - mkdocs_quiz

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js


